= Programy

Pokud chcete doma či při cvičení používat vlastní počítač, nutně budete
potřebovat tyto programy:

* http://openscad.org[OpenSCAD] 2019.05 nebo novější
* https://github.com/3DprintFIT/netfabb-basic-download/releases[netfabb Basic]
* https://github.com/SoftFever/OrcaSlicer[OrcaSlicer]
* https://github.com/admesh/admesh[ADMesh] >= 0.98 (včetně devel balíků,
pokud instalujete z repozitářů)

Dále by se vám mohlo hodit:

* https://ultimaker.com/en/products/ultimaker-cura-software[Cura]
* http://meshlab.sourceforge.net/[Meshlab]
* https://www.danielgm.net/cc/[CloudCompare]
* https://github.com/admesh/ADMeshGUI[ADMeshGUI] na prohlížení STL souborů
* http://kisslicer.com/[KiSSlicer]

== Instalace v Linuxu

Doporučenou linuxovou distribucí je *Fedora*, protože obsahuje všechny
toto nástroje v repozitářích (kromě netfabbu, který není
open-source, ten ale najdete v oblíbeném repozitáři
http://rpmfusion.org/[RPM Fusion]).


=== Fedora

* Pro instalaci všech nástrojů a aplikací:
`# dnf install openscad-MCAD printrun admesh-devel admeshgui cloudcompare meshlab cura admeshgui`
* Pouze nezbytně nutné:
`# dnf install printrun openscad admesh-devel`
* netfabb Basic naleznete v repozitáři
http://rpmfusion.org/[RPM Fusion], jako `netfabb-basic`

* Pro OrcaSlicer použijte AppImage, který najdete v https://github.com/SoftFever/OrcaSlicer/blob/main/README.md#how-to-install[README]. Některé repozitáře obsahují i Flatpak verzi, ale není oficiálně podporovaná.

Používejte podporovanou verzi Fedory, jinak budete mít staré verze
programů.

=== Ostatní distribuce

Existuje určitá pravděpodobnost, že některé tyto programy jsou k
dispozici přes balíčkovací systém vaší distribuce. Pokud je v distribuci
nenajdete, postupujte podle instrukcí na webu aplikace.

* http://www.openscad.org/downloads.html#linux[Instalace OpenSCADu]
* https://github.com/3DprintFIT/netfabb-basic-download/releases[Stažení
netfabbu]
* http://reprap.org/wiki/Printrun#GNU.2FLinux_.26_Distros[Instalace
Printrunu]
* https://github.com/SoftFever/OrcaSlicer/blob/main/README.md#how-to-install[Instalace
OrcaSliceru]
* https://github.com/admesh/admesh/blob/master/INSTALL[Instalace
ADMeshe]
* https://github.com/admesh/ADMeshGUI#building[Instalace ADMeshGUI]

== Instalace na macOS

ADMesh je třeba zkompilovat stejně jako na Linuxu, případně lze použít
homebrew. Stejně tak pro
https://github.com/admesh/ADMeshGUI#building[ADMeshGUI].

https://github.com/3DprintFIT/netfabb-basic-download/releases[Netfabb]
je třeba stáhnout z našeho GitHubu.

Warning: Netfabb Basic nefunguje na Mac počítačích s ARM procesorem. Jako alternativu na cvičení můžete použít školní počítače nebo virtualizaci.

Ostatní software má vždy svou MacOS variantu ke stažení na stránce
programu.

Další možností je instalace (stažení) a spuštění přímo ze zdrojových
kódů aplikace (odkazy v linuxové části).

== Instalace na Windows

Pro Windows je všechen software, až na výjimky, připraven v
předkompilované verzi. Ve většině případů na stránkách programu
uvedených výše.

Výjimky:

* https://github.com/admesh/admesh/releases[Předkompilovaný ADMesh pro
Windows]

Netfabb Basic: Můžete použít
https://www.netfabb.com/try-netfabb-premium-now[Oficiální Trial verzi
pro Windows], která po vypršení funguje jako Basic, nebo starší verzi
Netfabb Basic
https://github.com/3DprintFIT/netfabb-basic-download/releases[z našeho
GitHubu].

Pro připojení některých tiskáren je třeba instalovat všelijaké drivery.
Na cvičení to ale není potřeba, k tiskárnám se připojíte přes webové rozhraní.
