= Hodnocení

Celkové hodnocení se skládá z bodů získaných v průběhu semestru. Nekoná
se žádná zkouška, ani se nepíše žádný test. Zde je celková skladba bodů,
které můžete získat:

* *30* bodů za úlohy na cvičeních
* *30* bodů za parametrický úkol v OpenSCADu
* *40* bodů za semestrální práci

Cvičící smí, ale není povinen, udělit další body nad rámec celkového
součtu 100 bodů za mimořádnou aktivitu nad rámec povinností.

TIP: Garant předmětu může studentovi část hodnocení předmětu nahradit za
alternativní práci na svobodném softwaru souvisejícím s 3D tiskem a/nebo práci
na studijních materiálech. Jedná se ale vždy o individuální dohodu, není možné
očekávat toto automaticky.

Vaše hodnocení naleznete na
https://grades.fit.cvut.cz/courses/BI-3DT.1/my-classification[grades.fit.cvut.cz].

== Celkové hodnocení

Hodnocení se řídí Studijním a zkušebním řádem ČVUT.

[options="autowidth"]
|====================================================
<h| Známka  <h| Bodové rozmezí  <h| Slovní hodnocení
  | A        ^|  90 a více        | výborně
  | B        ^|  80-89            | velmi dobře
  | C        ^|  70-79            | dobře
  | D        ^|  60-69            | uspokojivě
  | E        ^|  50-59            | dostatečně
  | F        ^|  méně než 50      | nedostatečně
|====================================================
