# Build pages and deploy to courses.fit.cvut.cz
course-pages:
  stage: deploy
  image: ${CI_REGISTRY}/course-pages/course-pages:stable
  script:
    - course-pages public/
  artifacts:
    paths:
      - public
    expire_in: 1 hour
