= Problémy při tisku
:toc:

== Na tiskárnu se nelze připojit

Pokud se nelze na tiskárnu připojit...

1. Zkontrolujte, že je počítač připojen k síti a že sedíte u školního počítače (z vlastního počítače se nelze připojit).
2. Ujistěte se, že se připojujete na správnou adresu. Zadávejte do počítače explicitně celou adresu, včetně `http://`.
4. Tiskárnu restartujte jejím vypnutím a opětovným zapnutím (vypojením a zapojením do elektřiny).

Pokud nic z toho nepomůže, požádejte cvičícího o pomoc.

== Z extruderu není vytlačován žádný plast

Pokud jste právě zavedli filament, chvíli to trvá, než se z extruderu vytlačí veškerý vzduch a začne se vytlačovat plast.

Jemně uchopte filament při extrudování a zkontrolujte hmatem, zda je filament bez problémů vtahován dovnitř extruderu.
Pokud je filament na místě a nejde dovnitř, znamená to, že je extruder ucpaný.

1. Zkontrolujte správnost nastavených teplot.
2. Zkuste filament vyjmout a zavést znova.

Pokud nic nepomůže, je nutné extruder vyčistit.
Přivolejte cvičícího pro asistenci.

== Tiskárna vydává divný hlasitý zvuk

Tiskárny jsou obecně velmi hlučné.
Pokud si však všimnete velmi nezvyklého hluku při tisku, nebojte se přivolat cvičícího.

== Z tiskárny se kouří / hoří / je viditelně fyzicky poškozená

Okamžitě upozorněte cvičícího. I pokud si nejste jisti, zda je to problém, raději přivolejte cvičícího. Nestačí se hlásit, rovnou křičte.
https://www.thissmarthouse.net/dont-burn-your-house-down-3d-printing-a-cautionary-tale/[Požár tiskárny není neobvyklá věc].
