= Problémy při tisku
Marián Hlaváč <marian.hlavac@fit.cvut.cz>
:toc:

== Na tiskárnu se nelze připojit.

Pokud se nelze na tiskárnu připojit...

1. Zkontrolujte, že je počítač připojen k síti a že sedíte u školního počítače (z vlastního počítače se nelze připojit).
2. Ujistěte se, že se připojujete na správnou adresu. Zadávejte do počítače explicitně celou adresu, včetně `http://`.
4. Tiskárnu restartujte jejím vypnutím a opětovným zapnutím (vypojením a zapojením do elektřiny).

Pokud nic z toho nepomůže, požádejte cvičícího o pomoc.

== Nemohu se k tiskárně přihlásit.

Ujistěte se, že přihlašovací údaje zadáváte správně (caps lock, cz/en klávesnice). Přihlašovací údaje jsou:

Jméno:: student
Heslo:: _sdělí cvičící_

== Z extruderu nevytéká žádný plast.

Pokud jste právě zavedli filament, chvíli to trvá, než se z extruderu vytlačí veškerý vzduch a začne vytékat plast.

Jemně uchopte filament při extrudování a zkontrolujte hmatem, zda filament bez problémů je vtahován dovnitř extruderu.
Pokud je filament na místě a nejde dovnitř, znamená to, že je extruder ucpaný.

1. Zkontrolujte správnost nastavených teplot
2. Zkuste filament vyjmout a zavést znova

Pokud nic nepomůže, je nutné extruder vyčistit.
Přivolejte cvičícího pro asistenci.

== Tiskárna vydává divný hlasitý zvuk.

Tiskárny jsou obecně velmi hlučné.
Pokud si však všimnete velmi nezvyklého hluku při tisku, nebojte se přivolat cvičícího.

== Z tiskárny se kouří / hoří / je viditelně fyzicky poškozená.

Okamžitě upozorněte cvičícího. I pokud si nejste jistí, zda je to problém, raději přivolejte cvičícího. Nestačí se hlásit, rovnou křičte.